# single line comment starts with the # symbol

# this is the first make target, so it is the default.
# it depends on two other targets as the dependencies
default: build run


build: run

run:
	python3 helloworld.py

time_now: 
	python3 time_now.py

clean:
	rm *.pyc
